# Cirun configuration for crypto signal bot
runners:
  - name: "aws-runner"
    cloud: "aws"
    
    # Cheap and sufficient for Python bot
    instance_type: "t3.micro"  # 2 vCPU, 1GB RAM
    
    # Ubuntu 22.04 LTS AMI for us-east-2 (Ohio)
    machine_image: "ami-09748244b630b1bb5"  # Ubuntu 22.04 LTS x86_64
    
    # Labels to use in workflow
    labels:
      - "cirun-aws"
    
    # Use on-demand instances (more reliable than spot)
    preemptible: false
    
    # Keep runner alive for 1 minute between jobs (matches your cron schedule)
    idle_time: 60  # 1 minute - keeps runner warm for frequent runs
    
    # Use same region as your S3 bucket for faster sync
    region: "us-east-2"