# Cirun configuration for crypto signal bot
runners:
  - name: "aws-runner"
    cloud: "aws"
    
    # Cheap and sufficient for Python bot
    instance_type: "t3.micro"  # 2 vCPU, 1GB RAM
    
    # Ubuntu 22.04 LTS AMI for us-east-2 (Ohio)
    machine_image: "ami-0ea3c35c5c3284d82"  # Ubuntu 22.04 LTS x86_64
    
    # Labels to use in workflow
    labels:
      - "cirun-aws"
    
    # Use spot instances for 70% cost savings
    preemptible: true
    
    # Auto-terminate quickly to save costs
    idle_time: 45
    
    # Use same region as your S3 bucket for faster sync
    region: "us-east-2"